;========================================================
;	FLOPPY DISK INITIAL SPECIFICATION SEQUENCES	=
;========================================================
    if (BOOT8X and LOADER) or (FLOPPY8 and not LOADER)
	LEA	CS:BX,SPEC8	;Point to 8 inch floppy drive specifications
	MOV	CX,0300h	;Set up 3 bytes in controller
	CALL	EXEC1
    endif
    if (BOOT5X and LOADER) or (FLOPPY5 and not LOADER)
	MOV	AL,FD5TYPE	;Set up I/O ports with correct floppy type
	CALL	FIX58		; and turn motors on
	LEA	CS:BX,SPEC5	;Get 5 1/4 inch floppy drive specifications
	MOV	CX,0300h	;Set up 3 bytes in controller
	CALL	EXEC1
    endif
	JMPS	D1INITZ		;Skip past data area
;
    if (BOOT8X and LOADER) or (FLOPPY8 and not LOADER)
SPEC8	DB	FD_SPEC		;Specify command
	DB  (SRT8 shl 4) + HUT8	;Step rate, Head unload times
	DB	HDLT8 shl 1	;Head load time
    endif
    if (BOOT5X and LOADER) or (FLOPPY5 and not LOADER)
SPEC5	DB	FD_SPEC		;Specify command
	DB  (SRT5 shl 4) + HUT5	;Step rate, Head unload times
	DB	HDLT5 shl 1	;Head load time
    endif
  if LOADER
D1INITZ:
  endif
SIGNON1	RS 0
    if (FLOPPY8 and not LOADER)
	DB	'Disk 1  (8 inch floppy)  ' ;Show 8 inch drives included
      if not (DISK2 or DISK3)
	DB	'A:  B:'
	  if FPY8X4
	DB	'  C:  D:'
	  endif
      endif
      if (DISK2 or DISK3)
	DB	'I:  J:'
	  if FPY8X4
	DB	'  K:  L:'
	  endif
      endif
	DB	CR,LF
    endif
    if (FLOPPY5 and not LOADER)
	DB	'Disk 1  (5-1/4" floppy)  ' ; 5 1/4 inch drives included
      if (DISK2 or DISK3)
	  if FLOPPY8
	DB	'K:  L:'
	  endif
	  if not FLOPPY8
	DB	'I:  J:'
	    if FPY5X4
	DB	'  K:  L:'
	    endif
	  endif
      endif
      if not (DISK2 or DISK3)
	  if FLOPPY8
	DB	'E:  F:'
	    if FPY5X4
	DB	'  G:  H:'
	    endif
	  endif
	  if not FLOPPY8
	DB	'A:  B:'
	    if FPY5X4
	DB	'  C:  D:'
	    endif
	  endif
      endif
	DB	CR,LF
    endif
    if not LOADER
	DB	0
;
D1INITZ:LEA	CS:BX,SIGNON1	;Point to signon for Disk 1
	CALL	PRINT		;Display it
    endif
