	program exampl
c
cc	This program is intended to provide a simple test to verify
c	the correct installation of SVS FORTRAN-77 under TriSoft CP/M-68K.
c
c	It serves no other useful purpose.
c
c	To execute this program simply enter:
c
c		A> FOR EXAMPLE ! EXAMPLE
c
c
c
	print 25
25	format (////////////
     *		,/,'      *********************************************** '
     *		,/,'      *********************************************** '
     *		,/,'      **                                           ** '
     *          ,/,'      **    FORTRAN-77 is correctly installed !!   ** '
     *		,/,'      **                                           ** '
     *		,/,'      *********************************************** '
     *		,/,'      *********************************************** '
     *		,////////)
c
	end
